kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: customrole-devspaces-2
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
rules:
  - verbs:
      - 'use'
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
